function srir_out = decorrelate_residual(srir_in, fs)
%DECORRELATE_RESIDUAL Decorrelate an SRIR residual with shared STFT phase.
%   The same deterministic frequency-dependent phase mask is applied to
%   every channel and STFT frame. This preserves inter-channel relationships
%   while reducing waveform correlation with the input. Input and output
%   use the project convention samples x channels.

num_samples = size(srir_in, 1);
num_channels = size(srir_in, 2);

if num_samples < 4 || ~any(srir_in(:))
    srir_out = srir_in;
    return
end

window_length = min(num_samples, max(4, round(0.020 * fs)));
window_length = window_length - mod(window_length, 4);
overlap_length = 3 * window_length / 4;
fft_length = 2^nextpow2(window_length);
analysis_window = hann(window_length, 'periodic');
padding_length = fft_length;
zero_padding = zeros(padding_length, num_channels, 'like', srir_in);
srir_padded = [zero_padding; srir_in; zero_padding];

srir_spectrum = stft( ...
    srir_padded, ...
    fs, ...
    'Window', ...
    analysis_window, ...
    'OverlapLength', ...
    overlap_length, ...
    'FFTLength', ...
    fft_length, ...
    'FrequencyRange', ...
    'onesided');

phase_stream = RandStream('mt19937ar', 'Seed', 20);
phase_angles = 2 * pi * rand(phase_stream, size(srir_spectrum,1), 1) - pi;
phase_angles(1) = 0;
phase_angles(end) = 0;
phase_mask = reshape(exp(1i * phase_angles), [], 1, 1);

srir_padded_out = istft( ...
    srir_spectrum .* phase_mask, ...
    fs, ...
    'Window', ...
    analysis_window, ...
    'OverlapLength', ...
    overlap_length, ...
    'FFTLength', ...
    fft_length, ...
    'FrequencyRange', ...
    'onesided', ...
    'ConjugateSymmetric', ...
    true);

crop_idx = padding_length + (1:num_samples);
srir_out = real(srir_padded_out(crop_idx,:));

input_energy = sum(abs(srir_in).^2, 'all');
output_energy = sum(abs(srir_out).^2, 'all');
if output_energy > 0
    srir_out = srir_out * sqrt(input_energy / output_energy);
end

end
