function [srir_new, path_info] = extrapolate_srir_single_room_baseline( ...
    srir_orig, ...
    fs, ...
    geom, ...
    order_ISM, ...
    window_param, ...
    flag, ...
    residual_scale_param)
%EXTRAPOLATE_SRIR_SINGLE_ROOM_BASELINE Run the one-room SRIR baseline.
%   The caller supplies the geometry; coupled-room comparisons use one virtual
%   room that spans both physical rooms.

%% Calculate original and target paths

    paths_single_room.orig = ism_calculate( ...
        geom.rec.orig.pos, ...
        geom.src.orig.pos, ...
        order_ISM, ...
        geom.room_s.dim, ...
        fs, ...
        geom.c, ...
        flag.plot_ism);

    paths_single_room.tar = ism_calculate( ...
        geom.rec.tar.pos, ...
        geom.src.tar.pos, ...
        order_ISM, ...
        geom.room_s.dim, ...
        fs, ...
        geom.c, ...
        flag.plot_ism);

%% Match paths and resynthesise

    path_info = calc_path_info_single_room(paths_single_room);

    [srir_new, path_info] = srir_resynthesis_withBeamform( ...
        srir_orig, ...
        path_info, ...
        window_param, ...
        flag, ...
        residual_scale_param, ...
        fs);
end
