function [srir_new, path_info] = extrapolate_srir_coupled_room( ...
    srir_orig, ...
    fs, ...
    idx_rec_orig, ...
    idx_rec_tar, ...
    geom, ...
    order_ISM, ...
    window_param, ...
    flag, ...
    residual_propagation_gain_param, ...
    zoom_param, ...
    residual_scale_param)
%EXTRAPOLATE_SRIR_COUPLED_ROOM Move an SRIR between coupled-room positions.
%   It matches paths, edits arrivals, adjusts the residual, and mixes the
%   result at the target receiver position.


    orig_in_room1 = idx_rec_orig <= 50;
    tar_in_room1 = idx_rec_tar <= 50;
    orig_in_room2 = ~orig_in_room1;
    tar_in_room2 = ~tar_in_room1;

%% path info calc

    [path_info_orig, path_a2r_orig] = calculate_position_path_info( ...
        idx_rec_orig, ...
        geom.src.orig.pos, ...
        geom.rec.orig.pos, ...
        geom, ...
        fs, ...
        order_ISM, ...
        flag.plot_ism);

    [path_info_tar, path_a2r_tar] = calculate_position_path_info( ...
        idx_rec_tar, ...
        geom.src.tar.pos, ...
        geom.rec.tar.pos, ...
        geom, ...
        fs, ...
        order_ISM, ...
        flag.plot_ism);

    % Combine the independently calculated original/target descriptors into
    % the standard path_info consumed by the resynthesis function.
    path_info = combine_path_info_orig_tar(path_info_orig, path_info_tar);

    path_info.gain = calculate_arrival_propagation_gains(path_info);


%% Extract Arrivals

    [arrival_set, srir_residual] = srir_extract_arrivals_withBeamform(srir_orig, path_info, window_param, flag);
    path_info.was_extracted = arrival_set.was_extracted;


%% Rotate and scale extracted arrivals

    processing_idx = [arrival_set.reflection_idx arrival_set.direct_idx];
    for i = processing_idx
        if isempty(arrival_set.audio{i})
            continue
        end

        % Rotation of arrivals
        arrival_set.audio{i} = rotate_srir_arrival( ...
            arrival_set.audio{i}, ...
            path_info.doa_orig_deg(:,i), ...
            path_info.doa_tar_deg(:,i));

        % Scaling of arrivals
        arrival_set.audio{i} = scale_srir_arrival(arrival_set.audio{i}, path_info.gain(i));
    end




%% Residual Zooming

    zoom_order = sqrt(size(srir_residual,2)) - 1;
    path_info.residual_zoom.enabled = logical(zoom_param.enabled) && ~(orig_in_room1 && tar_in_room1);
    path_info.residual_zoom.was_applied = false;
    path_info.residual_zoom.coord_change = reshape(zoom_param.coord_change, 1, []);
    path_info.residual_zoom.order = round(zoom_order);

    plot_zoom_directions = true;
    if isfield(flag, 'plot_zoom_directions')
        plot_zoom_directions = flag.plot_zoom_directions;
    end

    if path_info.residual_zoom.enabled && any(srir_residual(:) ~= 0)
        [srir_residual, ~, ~] = zooming( ...
            srir_residual, ...
            path_info.residual_zoom.order, ...
            path_info.residual_zoom.coord_change, ...
            plot_zoom_directions, ...
            zoom_param.preserve_omni_rms);
        path_info.residual_zoom.was_applied = true;
    end


%% Residual Scaling 

    if orig_in_room1 && tar_in_room1
        % Room 1 -> Room 1 does not use residual scaling.
        residual_scale_param.mode = "off";
        residual_scale_param.gain = 1;


    elseif orig_in_room2 && tar_in_room2
        % Room 2 -> Room 2 selects a propagation-gain model for the residual.
        residual_scale_param.gain = calculate_residual_propagation_gain( ...
            path_info, ...
            path_a2r_orig, ...
            path_a2r_tar, ...
            residual_propagation_gain_param);


    else
        % Room 1 <-> Room 2 retains the combined deterministic path gains.
        % Its residual uses the matched direct-path distance ratio.
        residual_scale_param.gain = calculate_residual_propagation_gain( ...
            path_info, ...
            path_a2r_orig, ...
            path_a2r_tar, ...
            residual_propagation_gain_param);
    end

    [srir_residual, path_info.residual_scale] = scale_srir_residual( ...
        srir_residual, ...
        path_info.toa.orig_samp(arrival_set.direct_idx), ...
        residual_scale_param, ...
        fs);


%% Reposition and mix

    [srir_new, path_info.was_added] = srir_resynthesize_from_arrivals( ...
        arrival_set, ...
        srir_residual, ...
        path_info.toa.tar_samp, ...
        window_param.pre_samp);

end





function [path_info, path_a2r] = calculate_position_path_info( ...
    idx_rec, src_pos, rec_pos, geom, fs, order_ISM, plot_ism)
%CALCULATE_POSITION_PATH_INFO Build the path list for one receiver position.

    path_a2r = [];

    if idx_rec > 50
        % Current source-receiver configuration in room 2
        paths_s2a = ism_calculate( ...
            geom.aperture.pos, ...
            src_pos, ...
            order_ISM, ...
            geom.room_s.dim, ...
            fs, ...
            geom.c, ...
            plot_ism);

        path_a2r = calculate_aperture_to_receiver_propagate( ...
            rec_pos, ...
            geom.aperture.pos, ...
            fs, ...
            geom.c);

        path_info = calc_path_info_coupled_room( ...
            paths_s2a, ...
            path_a2r, ...
            fs);
    else
        % Current source-receiver configuration in room 1
        path_info = ism_calculate( ...
            rec_pos, ...
            src_pos, ...
            order_ISM, ...
            geom.room_s.dim, ...
            fs, ...
            geom.c, ...
            false);
    end
end
