function [] = heatmap_plot_hammer(az,el,z)
%HEATMAP_PLOT_HAMMER Plot spherical samples on a flat Aitoff heatmap.
%   Azimuth, elevation, and sample values are supplied as matching vectors.


%% Interpolate the spherical data

% fig = figure;%('Position', [40, 40, 650, 500]);
x = az;
y = el;

xlin = linspace(min(x),max(x),180*2);
ylin = linspace(min(y),max(y),90*2);
[X,Y] = meshgrid(xlin,ylin);

coordinate_points = isfinite(x) & isfinite(y);
valid_points = coordinate_points & isfinite(z);

if nnz(valid_points) >= 3
    Z = griddata(x(valid_points),y(valid_points),z(valid_points),X,Y,'cubic');
    valid_grid = griddata( ...
        x(coordinate_points), ...
        y(coordinate_points), ...
        double(valid_points(coordinate_points)), ...
        X, ...
        Y, ...
        'nearest');
    Z(valid_grid < 0.5) = NaN;
else
    Z = nan(size(X));
end

%% Configure the projected heatmap

% surf(X,Y,Z,'EdgeColor','none')
% worldmap('World')
% axesm('hammer', 'Frame', 'on', 'Grid', 'on');
axesm( ...
    'aitoff', ...
    'Frame', ...
    'on', ...
    'Grid', ...
    'on', ...
    'GLineStyle', ...
    '--', ...
    'GColor', ...
    [0.5 0.5 0.5], ...
    'MLineLocation', ...
    45, ...
    'PLineLocation', ...
    30, ...
    'FLineWidth', ...
    1, ...
    'FEdgeColor', ...
    [0.5 0.5 0.5], ...
    'Origin', ...
    [0 0 0]);
% pcolorm(X,Y,Z) % a pseudo-color plot of obs data on the projected grid
pcolorm(Y,X,flip(Z,2)) % a pseudo-color plot of obs data on the projected grid
mlabel('on');
plabel('on');
setm( ...
    gca, ...
    'MLabelLocation', ...
    45, ...
    'PLabelLocation', ...
    30, ...
    'MLabelParallel', ...
    'equator', ...
    'PLabelMeridian', ...
    'prime', ...
    'FontColor', ...
    [0.5 0.5 0.5], ...
    'FontSize', ...
    10);

%% Add custom grid labels

% Turn off default labels
mlabel('off');
plabel('off');

semiTransparentGrey = [0.5, 0.5, 0.5, 0.5];

% Manually add meridian labels
for lon = -180:45:180
    h = textm( ...
        0, ...
        lon, ...
        sprintf('%d°', abs(lon)), ...
        'HorizontalAlignment', ...
        'center', ...
        'Color', ...
        semiTransparentGrey, ...
        'FontSize', ...
        10);
    % Shift position
    h.Position = h.Position + [0.05, -0.06, 0];
end

% Manually add parallel labels
for lat = -90:30:90
    if lat ~= 0
        h = textm( ...
            lat, ...
            0, ...
            sprintf('%d°', abs(lat)), ...
            'HorizontalAlignment', ...
            'center', ...
            'Color', ...
            semiTransparentGrey, ...
            'FontSize', ...
            10);
        % Shift position
    h.Position = h.Position + [0.05, -0.06, 0];
    end
end


% axis tight;
% xlabel('Azimuth (°)');
% ylabel('Elevation (°)');

% shading interp
% view ([0 90])
% s.EdgeColor = 'none';

% set(gca, 'ActivePositionProperty' , 'position');

% originalSize = get(gca, 'Position');
% originalOuterBoundary = get(gca, 'outerposition');

% set(gca, 'Position', originalSize);
% set(gca, 'outerposition', originalOuterBoundary);

% colormap(flipud(parula))
% set(gca, 'XDir', 'reverse', 'YTick', -75:75:75, 'XTick', -150:75:150); %%%% should that be -180:75:180   ???
% xlim([-180 180]);
% ylim([-90 90]);

% m = pbaspect('mode');
% m = 'manual';
% pbaspect([2 1 1])
% daspect([1 0.6 1]);

% box on
% set(gcf, 'Color', 'w');




% 
% if saveFigs == 1
% %     savefig(strcat('Figures301/deltaSpecDiff_order_',num2str(AmbiOrder),'_Both_Ears_ambiDFC_IRs_16020_1024tap_quadBias_',num2str(quadratureSFactor),'.fig'));
%     
%     set(gcf, 'Color', 'w');
% %     export_fig(sprintf('Figures301/deltaSpecDiff_order%d_bothEars_ambiDFC_IRs_16020_1024tap_quadBias%d.pdf',AmbiOrder,quadratureSFactor), '-pdf', '-q101', '-opengl');
%     
% %     
% %     colormap(gray);
% %     set(gcf, 'Color', 'w');
% %     export_fig(sprintf('Figures301/deltaSpecDiff_order%d_bothEars_ambiDFC_IRs_16020_1024tapGRAY.pdf',AmbiOrder), '-pdf', '-q101', '-opengl');
% end

%% Finalise the axes

tightmap
box off
axis off

end
